# Generated by Django 4.2.6 on 2023-10-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_input_mail_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='input_mail',
        ),
    ]
